# Generated by Django 3.2.5 on 2021-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apic', '0003_auto_20210816_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image1',
            field=models.CharField(max_length=1000),
        ),
    ]
